# PhenoPLIER
## Journal:
- id: doi:10.1038/s41467-023-41057-4
  type: paper
  image: images/articles/phenoplier.png
  description: Here we introduce the PhenoPLIER framework, an omnigenic approach that integrates genetic studies (GWAS/TWAS) with gene modules learned from expression data. PhenoPLIER provides 1) a regression framework that computes an association between gene modules and diseases, 2) a clustering approach that finds groups of diseases with shared transcriptomic properties, and 3) a gene module-based drug-repurposing method.
  buttons:
    - type: manubot
      link: https://greenelab.github.io/phenoplier_manuscript/
    - type: source
      text: Manuscript source
      link: https://github.com/greenelab/phenoplier_manuscript/
## Preprint:
- id: doi:10.1101/2021.07.05.450786
  remove: true
# CCC
## Journal:
- id: doi:10.1016/j.cels.2024.08.005
  type: paper
  image: images/articles/ccc.png
  description: This article introduces the Clustermatch Correlation Coefficient (CCC), an efficient, easy-to-use and not-only-linear coefficient based on machine learning models. CCC can detect biologically meaningful linear and nonlinear patterns missed by standard, linear-only correlation coefficients.
  buttons:
    - type: manubot
      link: https://greenelab.github.io/ccc-manuscript/
    - type: source
      text: Manuscript source
      link: https://github.com/greenelab/ccc-manuscript/
## Preprint:
- id: doi:10.1101/2022.06.15.496326
  remove: true
# Manubot AI Editor
## Journal:
- id: doi:10.1093/jamia/ocae139
  type: paper
  image: images/articles/manubot-ai-editor.png
  description: We developed the Manubot AI Editor, a plugin to the Manubot publishing infrastructure that uses manuscript section-specific prompts and OpenAI's models to automatically revise and improve the text.
  buttons:
    - type: manubot
      link: https://greenelab.github.io/manubot-gpt-manuscript/
    - type: source
      text: Manuscript source
      link: https://github.com/greenelab/manubot-gpt-manuscript
## Preprint:
- id: doi:10.1101/2023.01.21.525030
  remove: true
# Genetic studies through the lens of gene networks (review)
- id: pubmed:39575117
  type: paper
  image: images/articles/genetic-studies-networks-review.png
# omni-PLIER
- id: pubmed:39670386
  type: paper
  image: images/articles/omni-plier.png
# Chatbots in science
- id: doi:10.1038/d41586-024-02630-z
  type: paper
  image: images/articles/chatgpt-nature.png
# Probabilistic Colocalization...
## Journal:
- id: doi:10.1016/j.ajhg.2020.11.012
  type: paper
  image: images/articles/prob_coloc.png
## Preprint:
- id: doi:10.1101/2020.07.01.182097
  remove: true
# Exploiting the GTEx resources...
## Journal:
- id: doi:10.1186/s13059-020-02252-4
  type: paper
  image: images/articles/exploiting.png
## Preprint:
- id: doi:10.1101/814350
  remove: true
# Others
- id: pubmed:38879443
  remove: true
- id: pubmed:26223526
  remove: true
- id: pubmed:30668570
  remove: true
- id: pubmed:30395166
  remove: true
- id: pubmed:30357313
  remove: true
- id: pubmed:31036433
  remove: true
- id: pubmed:29800232
  remove: true
- id: pubmed:32917697
  remove: true
- id: pubmed:33308443
  remove: true
- id: pubmed:35391741
  type: paper
  image: images/articles/param-gene-module-clique.png
- id: pubmed:33499903
  remove: true
- id: pubmed:36441943
  type: paper
  image: images/articles/quality-control-gwas.png
- id: pubmed:36344522
  remove: true
- id: pubmed:36747665
  remove: true
- id: pubmed:38177845
  remove: true
- id: pubmed:37689782
  remove: true
- id: pubmed:39147814
  remove: true
- id: pubmed:39243756
  remove: true
- id: doi:10.1101/2024.11.08.622657
  type: paper
  image: images/articles/biclustering_twas.png
- id: pubmed:39605717
  remove: true
- id: doi:10.1016/S2213-2600(19)30055-4
  type: paper
  image: images/articles/asthma.png
- id: doi:10.1038/s41467-022-33628-8
  type: paper
  image: images/articles/asthma_endotypes.png
- id: pubmed:35027082
  type: paper
  image: images/articles/prs.png
- id: doi:10.1101/2020.11.12.373647
  remove: true
- id: doi:10.1126/sciadv.aba2083
  type: paper
  image: images/articles/phenomexcan.png
- id: doi:10.1093/bioinformatics/btaa111
  type: paper
  image: images/articles/dl4papers.png
- id: doi:10.1093/bioinformatics/bty925
  type: paper
  image: images/articles/ukbrest.png
- id: pmid:29800232
  type: paper
  image: images/articles/predicting-mirna.png
- id: doi:10.1093/bioinformatics/bty899
  type: paper
  image: images/articles/clustermatch.png
- id: doi:10.1371/journal.pgen.1007889
  type: paper
  image: images/articles/multixcan.png
- id: doi:10.1016/j.ins.2016.04.027
  type: paper
  image: images/articles/divcontrol.png
- id: doi:10.1093/bib/bbv054
  type: paper
  image: images/articles/webdemo-builder.png
- id: doi:10.1093/bib/bby037
  remove: true
- id: doi:10.1101/292649
  remove: true
- id: pmid:30357313
  remove: true
- id: doi:10.1038/s43588-023-00453-y
  type: paper
  image: images/articles/high-dim-diseases.png
- id: doi:10.4018/978-1-61520-763-3.ch006
  image: images/articles/faia.png
  type: book
- id: isbn:978-987-25855-9-4
  image: images/articles/faia2.png
  title: 'FAIA: Un framework para el desarrollo de agentes inteligentes'
  link: https://www.worldcat.org/isbn/9789872585594
  type: book
